# Generated by Django 3.1.4 on 2021-01-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='books.Genre'),
        ),
    ]
